/********************************************************************
* src/dictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/dictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledictionary();
extern void G__cpp_setup_inheritancedictionary();
extern void G__cpp_setup_typetabledictionary();
extern void G__cpp_setup_memvardictionary();
extern void G__cpp_setup_globaldictionary();
extern void G__cpp_setup_memfuncdictionary();
extern void G__cpp_setup_funcdictionary();
extern void G__set_cpp_environmentdictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/jdb/Logger.h"
#include "include/jdb/Reporter.h"
#include "include/jdb/XmlConfig.h"
#include "include/jdb/ChainLoader.h"
#include "include/jdb/HistoBook.h"
#include "include/jdb/TreeAnalyzer.h"
#include "include/jdb/HistoAnalyzer.h"
#include "include/jdb/LoggerConfig.h"
#include "include/jdb/StringUtils.h"
#include "include/jdb/Utils.h"
#include "include/jdb/ConfigPoint.h"
#include "include/jdb/ConfigRange.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictionaryLN_TDirectory;
extern G__linked_taginfo G__dictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__dictionaryLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__dictionaryLN_string;
extern G__linked_taginfo G__dictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_jdb;
extern G__linked_taginfo G__dictionaryLN_jdbcLcLLogger;
extern G__linked_taginfo G__dictionaryLN_jdbcLcLLoggercLcLNullStream;
extern G__linked_taginfo G__dictionaryLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_TCanvas;
extern G__linked_taginfo G__dictionaryLN_TLegend;
extern G__linked_taginfo G__dictionaryLN_TXMLNode;
extern G__linked_taginfo G__dictionaryLN_TXMLDocument;
extern G__linked_taginfo G__dictionaryLN_jdbcLcLXmlConfig;
extern G__linked_taginfo G__dictionaryLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictionaryLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_jdbcLcLReporter;
extern G__linked_taginfo G__dictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__dictionaryLN_TFile;
extern G__linked_taginfo G__dictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_TH1;
extern G__linked_taginfo G__dictionaryLN_TChain;
extern G__linked_taginfo G__dictionaryLN_jdbcLcLChainLoader;
extern G__linked_taginfo G__dictionaryLN_jdbcLcLTaskTimer;
extern G__linked_taginfo G__dictionaryLN_jdbcLcLTaskProgress;
extern G__linked_taginfo G__dictionaryLN_jdbcLcLHistoBins;
extern G__linked_taginfo G__dictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__dictionaryLN_TH2;
extern G__linked_taginfo G__dictionaryLN_TH3;
extern G__linked_taginfo G__dictionaryLN_jdbcLcLHistoBook;
extern G__linked_taginfo G__dictionaryLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_jdbcLcLLoggerConfig;

/* STUB derived class for protected member access */
